[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  CI = "false"
  ESLINT_NO_DEV_ERRORS = "true"
  ESLINT_NEXT_NO_DEV_ERRORS = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 